### ISSUE TITLE
Question codes have divergent texts

### ISSUE THREAD

**Issue by kevinhu** [coursetable/ferry#76]
The Fall 2020 course evaluations appear to have mismatches in some question texts:

```
Traceback (most recent call last):
  File "./ferry/transform.py", line 155, in <module>
    ) = import_evaluations(
  File "/home/app/ferry/ferry/includes/transform_import.py", line 735, in import_evaluations
    raise database.InvariantError(
ferry.database.database_utilities.InvariantError: Error: question codes YC401, YC401-YCWR, YC403, YC403-YCWR, YC409, YC409-YCWR have divergent texts
```

**Comment by kevinhu** [comment]
Cause of the issue seems to be addition of the "Your anonymous response..." disclaimer.

```
YC401

  What knowledge, skills, and insights did you develop by taking this course?\n(Your anonymous response to this question may be viewed by Yale College students, faculty, and advisers to aid in course selection and evaluating teaching.)

  What knowledge, skills, and insights did you develop by taking this course?


YC401-YCWR

  What knowledge, skills, and insights did you develop by taking this course?

  What knowledge, skills, and insights did you develop by taking this course? (Your anonymous response to this question may be viewed by Yale College students, faculty, and advisers to aid in course selection and evaluating teaching.)


YC403

  What are the strengths and weaknesses of this course and how could it be improved?

  What are the strengths and weaknesses of this course and how could it be improved?\n(Your anonymous response to this question may be viewed by Yale College students, faculty, and advisers to aid in course selection and evaluating teaching.)


YC403-YCWR
  
  What are the strengths and weaknesses of this course and how could it be improved?

  What are the strengths and weaknesses of this course and how could it be improved? (Your anonymous response to this question may be viewed by Yale College students, faculty, and advisers to aid in course selection and evaluating teaching.)


YC409

  Would you recommend this course to another student? Please explain.

  Would you recommend this course to another student? Please explain.\n(Your anonymous response to this question may be viewed by Yale College students, faculty, and advisers to aid in course selection and evaluating teaching.)


YC409-YCWR
  
  Would you recommend this course to another student? Please explain.

  Would you recommend this course to another student? Please explain. (Your anonymous response to this question may be viewed by Yale College students, faculty, and advisers to aid in course selection and evaluating teaching.)
```
